version: "3.5"

#Docker Networks
networks:
    internal:
        driver: bridge
        name: internal
    external:
        driver: bridge
        name: external

# Docker Volumes
volumes:
    bitwardenrs_data:
        name: bitwardenrs_data

# Docker services
services:

    # Bitwarden server for raspberry pi
    bitwardenrs:
        image: bitwardenrs/server:latest
        container_name: bitwardenrs
        restart: always
        tty: true
        stdin_open: true
        volumes:
            - bitwardenrs_data:/data/
        ports:
            - "80:80"
        networks:
            - internal
            - external